[View in Colaboratory](https://colab.research.google.com/github/namitkapoor13/Python-Practice/blob/master/Intro_to_Python.ipynb)

In [0]:
print (4+5)

9


In [0]:
height = 1.78
weight = 64
bmi = weight / (height **2)
print (bmi)
type (height)

20.1994697639


float

In [0]:
x= 'I love'
y= ' Pizza'
print (x+y)

I love Pizza


In [0]:
x = 5.5
b= 1
y = x+b
z = True
a= False
type(y)
print(a+z)
aa=False


1


In [0]:
# Several variables to experiment with
savings = 100
factor = 1.1
desc = "compound interest"

# Assign product of factor and savings to year1

year1 = (savings * factor)
# Print the type of year1
type(year1) #no output?

# Assign sum of desc and desc to doubledesc
doubledesc= desc + desc

# Print out doubledesc
print(type(year1))
print(doubledesc)
type(year1)



<type 'float'>
compound interestcompound interest


float

In [0]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!") #cannot concatenate strings and float(other data types together), we have to convert it into str. Str(variable). Like this it is int(),float(),bool()

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float=float(pi_string)

I started with $100 and now have $194.87171. Awesome!


In [0]:
print('Hey'+('Hey')*2+'Good')

HeyHeyHeyGood


In [0]:
#List Example. Its inconvinient to create multiple variable of again and again. Hence, LISTS!!!
#Collection of  values. and can contain any data type

list1 = ['mom',111.2,'dad',111.5]


#can contain list itself
#list is also a data-type
list2 =['son',123.3,'daughter','1234.5']
list3=[list1,list2]
print(list3)
type(list3)

list4 = [1+2,'a'*2,3]
print(list4)

[['mom', 111.2, 'dad', 111.5], ['son', 123.3, 'daughter', '1234.5']]
[3, 'aa', 3]


In [0]:
#subsetting lists
list1 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
#index based search starting from 0 to n. Negative index based search is used to get end of list. -1 represents last element.
print(list1[0]) #will return mom
print(list1[-1])#will return 1234.5

mom
1234.5


In [0]:
#list slicing. Selecting range within list. Syntax : listname[start:end]. It will return records from start index to (end-1) index
list1 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
list2 = list1[3:5]
print(list2)
print(list1[:4]) #if start is not specified, It will begin from 0 index
print(list1[1:]) #if end is not specified, it will stop at end of list
sum1=list1[1] + list2[0] #operator use on list elements
print(sum1)

[111.5, 'son']
['mom', 111.2, 'dad', 111.5]
[111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]
222.7


In [0]:
list1 =[['mom',111.2,'dad',111.5],['son',123.3,'daughter','1234.5'],['son',123.3,'daughter',1234.5]] #list of lists
x= list1[1][1:] #using zero based indexing it looks for 1 position and then, select the value from 1:till end.
print(x)
y=list1[0][1]+list1[2][-1] #operator use on basis of index value
print(y)

[123.3, 'daughter', '1234.5']
1345.7


In [0]:
#list manipulation
list1 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
#changing values of list
list1[-1]=123.45
print(list1)
list1[2:4]=['papa',111.45]
print(list1)

['mom', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 123.45]
['mom', 111.2, 'papa', 111.45, 'son', 123.3, 'daughter', 123.45]


In [0]:
#adding or removing list elements
list1 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
list_add = list1 + ['son2',22.5]
print(list_ext)
del(list1[:2])
print(list1)

['mom', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5, 'son2', 22.5]
['dad', 111.5, 'son', 123.3, 'daughter', 1234.5]


In [0]:
#copying a list.
list1 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
x = list1 
x[0]='mother'
print(x)
print(list1) #we have assigned a variable x to earlier created list1. 
#so whatever changes in x, it will also change for list1. since both are referencing the same objects.
#to copy a list, we have to use list(listname) or listname[:]
list2 = ['mom',111.2,'dad',111.5,'son',123.3,'daughter',1234.5]
y = list(list2)
z = list2[:]
# if we make changes to y. then list1 is not affected.
y[0]='mother'
print(y)
print(z)
print(list2)

['mother', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]
['mother', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]
['mother', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]
['mom', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]
['mom', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', 1234.5]


In [0]:
#functions #max() #round(number,[n digits]) where n is optional #int()bool()float() #type() and etc etc

p=round(1.9345678)
print(p)
x=round(1.9345001,4)
print(x)

#to get to know more about function we use : help(function_name) eg... : help(len)
y=complex(4,3)
print(y)

list1 = ['mom',111.2,'dad',111.5]

list2 = ['son',123.3,'daughter','1234.5']
list3= list1+list2
print(list3)
sort_asc = sorted(list3, reverse = False)
print(sort_asc)
sort_desc = sorted(list3, reverse = True)
print(sort_desc)

2.0
1.9345
(4+3j)
['mom', 111.2, 'dad', 111.5, 'son', 123.3, 'daughter', '1234.5']
[111.2, 111.5, 123.3, '1234.5', 'dad', 'daughter', 'mom', 'son']
['son', 'mom', 'daughter', 'dad', '1234.5', 123.3, 111.5, 111.2]


In [0]:
#methods : Functions on Python 'Objects'. Python objects are variabe of different type. List.
#eg: object of type str has methods like capitalize(), replace()
# float : bit_length() , conjugate()
#list : index(), count()
#syntax of method : object_name.method(parameters)

list1 = ['mom',111.2,'dad',111.5]

print(list1.index('mom')) #index position
print(list1.count('mom')) #count the number of occurence of parameter

y='sister'
print(y.capitalize()) #first letter capitalize
print(y.replace('s','T')) #replace 's' with 'T' all occurances of s.

list1.append('daughter')
print(list1)

0
1
Sister
TiTter
['mom', 111.2, 'dad', 111.5, 'daughter']


In [0]:
#packages : directory of python script. Pre-written scripts that we can use and utilize what all functions and methods it contains. 
#Each script in a package is a module
#not available by default. need to download from web and import them
# to install package we have to use pip: package maintainence system in python
#download get-pip.py
# go to http://pip.readthedocs.io/en/stable/installing/ . Download pip
# go to terminal and type : python get-pip.py
# install 'abc' package syntax : pip install abc
# to use 'abcdef' in our script, we have to import it first using: import abcdef
# to use a function count() in abc package we do : abc.count(parameter)
# we can give alias to package: import abcdef as a
                              # a.count(parameter)
  
# to import a specific function from a package we do : from package_name import function_name
#to import a function in subpackage of a package , then we do : from package_name.subpackage_name import function_name
import numpy  as np #numeric python package
list1=[1.23,2.34,3.45]
list2=[1.23,2.34,3.45] 
#calculations on list element is not possible. So we use numpy's function array()
length=np.array(list1) #converting lists in numpy array and storing it in a variable
breadth=np.array(list2)
area = length*breadth
area
#Numpy array can contain data of only one type
c=np.array([1,'sam',True]) #since this array contain multiple data type. when we run this code it will create all of them to str. THIS IS CALLED TYPE COERCION
print(c)
d=c+c
print(d)
list3= [1,2,3]
x=list3+list3 #list behavior of addition is different to np.array addition
print(x)
y=np.array([1,2,3])
z= y+y # hence, different types : different behavior
z

[1 2 1]
[2 4 2]
[1, 2, 3, 1, 2, 3]


array([2, 4, 6])

In [0]:
#numpy

x= np.array([1.1,2.1,3.1,4.1,5.1])
y=x[1]
y #will give value at index 1


#we can also use the result of an operation in an array to get further results. For Example:
z=np.array(y)
z #this will create an array based on the consisting value of y

#another example

a=np.array([2,4,6,5,7,8,4,3,2,45,43,0])
a>7 #this will create a boolean array listing true or false where a>7 is satisfied or not respectively.
b=a[a>7] #we can create a new array based on output of previous expression
b #THIS IS CALLED SUBSETTING. NUMPY SUBSETTING

array([ 8, 45, 43])

In [0]:
#numpy contd.

height = [70,71,72,73,74]
weight = [50,60,70,80,90]
hgt_arr= np.array(height) * 0.0254
wgt_arr = np.array(weight) * 0.453592
bmi = wgt_arr / (hgt_arr**2)
print(bmi)

light_people = bmi < 9.40
print(light_people) #bool array based on above equation
light_people_bmi = bmi[light_people] #subsetting array based on condition
print(light_people_bmi) 

[ 7.17417353  8.36820876  9.49360155 10.55461071 11.55518819]
[ True  True False False False]
[7.17417353 8.36820876]


In [0]:
#numpy contd.

height = [70,71,72,73,74]
weight = [50,60,70,80,90]
hgt_arr= np.array(height) 
wgt_arr = np.array(weight) 

# Print out sub-array of hgt_arr from index 1 up to and including index 3
print(hgt_arr[1:4])

[71 72 73]


In [0]:
# 2d Numpy Array

length = [70,71,72,73,74]
breadth = [1,2,3,4,5]

arr_2d = np.array([length,breadth])
print(arr_2d)

arr_2d.shape #shape of 2d array. (Rows,columns)

print(arr_2d[0][2]) #printing value at 0 row and 2 column
print(arr_2d[1][3:])# value 1st row and 3rd to last column

#these can also be done as 
print(arr_2d[0,2])
print(arr_2d[1,3:])
height = np.array([2,2,2,2,2])
multipli = arr_2d * height
print(multipli)

print(np.mean(arr_2d[0][:])) #mean of length
print(np.median(arr_2d[1,:])) #median of breadth

#It's always a good idea to check both the median and the mean, to get a first hunch for the overall distribution of the entire dataset.
#If mean is too high we can get a sense that the data is incorrect.
# other functions are 
# np.std(parameter) standard deviation
# np.corrcoef(parameter,parameter) correlation coefficient


[[70 71 72 73 74]
 [ 1  2  3  4  5]]
72
[4 5]
72
[4 5]
[[140 142 144 146 148]
 [  2   4   6   8  10]]
72.0
3.0


In [0]:
#Generate Data

length = np.round(np.random.normal(72,1,5),2) #syntax of normal function: np.random.normal(distribution mean, distribution standard deviation, no. of samples)
breadth = np.round(np.random.normal(3,1,5),2) #these 2 are examples of random distribution

arr_2d = np.column_stack((length,breadth)) #syntax of column stack function: np.column_stack(single_argument).
#In single argument we can give array seperated by comma and then combining them in one bracket
arr_2d


array([[73.42,  1.96],
       [70.88,  2.97],
       [74.03,  2.32],
       [72.36,  4.32],
       [71.26,  1.52]])